---
project_name: mrt
before:
  hooks:
    - go mod download
builds:
  - id: mrt
    main: ./main.go
    binary: mrt
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/meocode-labs/mrt/cmd.Version={{.Version}}
      - -X github.com/meocode-labs/mrt/cmd.Commit={{.Commit}}
    flags:
      - -trimpath
archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^CI'
